### ISSUE TITLE
Getting "Mixed content is not blocked: not secure" in Firefox

### ISSUE THREAD

**Issue by spencerriner** [rhazdon/hugo-theme-hello-friend-ng#116]
Hi - thanks for the theme, really great work! I'm having an issue with my Netlify deploy where I'm getting the padlock with the yellow caution icon saying "Parts of this page are insecure (such as images)." I've got a LetsEncrypt cert via Netlify and when I right-click to view Page Info > Media, there are only five images and they're all served over HTTPS. I have three other sites on Netlify and none of them are having this same issue, so I'm confident it's not my config on that end. 

Any advice/tips? Thank you!

Quick addition: this only happens on the home page, the About page and all posts seem to be fine. I wonder if it could be related to the SVG icons or something? It's such a minimal theme it's hard to figure what would be causing it.

**Comment by rhazdon** [comment]
Hi @spencerriner, 

honestly it looks like a misconfiguration of netlify... Could you do me a favour? Please open your web inspector and copy/paste the warnings from the console. The best would be, if you could paste the web address of your homepage, so I can take a look for you. 

Regarding your addition: I don't think so, because the icons aren't loaded from another pages. All svg icons the theme is using are shipped with the theme.
