### ISSUE TITLE
Theme change button not working and menu button appeared

### ISSUE THREAD

**Issue by eli-rodriguezperez** [rhazdon/hugo-theme-hello-friend-ng#16]
Hi!

I'm getting this thing where running the page locally gives no problems but after pushing it to github (I'm using github pages btw) the theme change button stops working and a new button appears with the menu icon but does nothing.

If it's of any help this is the [repo](https://github.com/eli-rodriguezperez/web) where I'm hosting the page and the [webpage](https://eli-rodriguez.com) itself where it's hosted.

**Comment by DuncanmaMSFT** [comment]
So this happens when the theme JavaScript doesn't run, either due to a syntax error or something that impacts the loading of the js file. In this case, you are running into a CORS issue with your js file. (From the Chrome console: "Subresource Integrity: The resource 'https://eli-rodriguezperez.github.io/web/js/bundle.min.cf7871ed49474a80ed457154d24e61f7881adbe0f9384951a74ac46b688a39a4dbfa68bc6d37baeb058186de354ead3487d4ee7f083ea4cba860c48600b694f3.js' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.")

**Comment by DuncanmaMSFT** [comment]
I believe the issue is that you have your baseURL set to `https://eli-rodriguezperez.github.io/web/` instead of `eli-rodriguez.com` and if you update that, you won't have the **CORS** issue

**Comment by DuncanmaMSFT** [comment]
And finally, this actually could be fixed with some changes to the theme. I'll put a PR in later today that makes these JS references use relative paths instead of absolute, in which case switching between the GitHub.io URL and your custom domain name won't cause this error.

**Comment by eli-rodriguezperez** [comment]
That's it, thank you so much!

**Comment by siyagule** [comment]
baseURL fix is the one, ta
