### ISSUE TITLE
Suggestion: unix path to match the site path

### ISSUE THREAD

**Issue by VivekRagunathan** [rhazdon/hugo-theme-hello-friend-ng#211]
First, this is the first theme I was very happy to see/try. Very clean. 🎉  Gives a feeling it is made for devs. So thanks. 🙏 

The unix path at the top is classy. What would be cool is to suffix the site path. For instance ...

- if you are in the about page, the path should show up as `> $ cd /home/about`
- if you are in the posts list page, it should show up as `> $ cd /home/posts` 
- if you are in the one of the posts, say _Markdown Syntax_, it should show up as `> $ cd /home/posts/mdsyn` (assuming there is a way to add a slug for the post .. or just `> $ cd /home/posts/markdown-syntax`)

Thanks

**Comment by xorbug** [comment]
Hi @VivekRagunathan, I think that's on purpose.
If you notice it's a link to the website home, it's not intended to show the current path (that's why `cd /home/`, because it takes you to home similarly to a shell, and similarly to most common websites that have a link to the home somewhere). So having a logo text named after the current path which actually links to another path (home) would be very inconsistent, while if it links to the current path would be useless (since you're already there).
Maybe an option could select the mode of operation...

**Comment by rhazdon** [comment]
Hi @VivekRagunathan, thank you very much for your idea. But I think that this wouldn't be that useful because a lot of people do not use this kind of logo text. :)
