### ISSUE TITLE
<br> doesn't work in md file

### ISSUE THREAD

**Issue by eazy-h** [rhazdon/hugo-theme-hello-friend-ng#218]
break line tag is not working!
can u make this possible?

**Comment by MKastuv** [comment]
I get around with:

&nbsp;
&nbsp;
&nbsp;

See if it works for you :)

**Comment by rhazdon** [comment]
Hi @eazy-h, 

your issue can not be fixed by the theme... It's a think of markdown. 

Take a look here: 

https://stackoverflow.com/questions/26626256/how-to-insert-a-line-break-br-in-markdown

or here

https://gist.github.com/shaunlebron/746476e6e7a4d698b373

or here

https://www.markdownguide.org/basic-syntax/#line-breaks.

Best regards :)
