### ISSUE TITLE
Stackoverflow social support

### ISSUE THREAD

**Issue by shashankKeshava** [rhazdon/hugo-theme-hello-friend-ng#54]
Can we add support for Stackoverflow social support ?

**Comment by JPYamamoto** [comment]
The project currently uses the icons provided by [Feather Icons](https://github.com/feathericons/feather). They don't currently have an icon for StackOverflow, however there's an open issue https://github.com/feathericons/feather/issues/231.
I don't know how @rhazdon feels about using icons from several sources, so that we could add the one provided by [Simple Icons](https://simpleicons.org/?q=stackoverflow).

**Comment by rjgonza** [comment]
Yikes, that's been opened for 2 years now. Do you have a pr to use simple icons?

**Comment by JPYamamoto** [comment]
I just sent a PR (https://github.com/rhazdon/hugo-theme-hello-friend-ng/pull/66) to add the StackOverflow icon from Simple Icons. However, for now you should take it only as a workaround. I think @rhazdon / the community should decide if using icons from mixed sources is the way to go.

**Comment by rjgonza** [comment]
Would be nice to have them from the same spot, but I don't think it needs to be limited to that.

**Comment by rhazdon** [comment]
I think in a long term view we should use only one icon source. Simple icons seems to be quite complete and up do date. I would consider to switch to it completely.  :)

**Comment by rhazdon** [comment]
@JPYamamoto Thanks for your first step for that. I have merged your PR with the Stackoverflow icon. :)
